appName: paymentservice
containerImage: gcr.io/google-samples/microservices-demo/paymentservice
imageTag: v0.2.3
containerPort: 50051
containerENV:
  - name: PORT
    value: "50051"
  

resourceCPU: 100m
resourceMemory: 64Mi
resourceLimitCPU: 200m
resourceLimitMemory: 128Mi


servicePort: 50051
containerPort: 50051
serviceType: ClusterIP
